/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utils_water_Water */

#ifndef _Included_com_utils_water_Water
#define _Included_com_utils_water_Water
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_utils_water_Water
 * Method:    doHeightBlob
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_utils_water_Water_doHeightBlob
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_utils_water_Water
 * Method:    doFree
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_utils_water_Water_doFree
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_utils_water_Water
 * Method:    doStart
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_utils_water_Water_doStart
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_utils_water_Water
 * Method:    flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_utils_water_Water_flush
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
